# ----------------------------------------------- # 

services:

  mariadb:

    build: requirements/mariadb
    container_name: mariadb
    restart: on-failure
    env_file: .env
    networks:
      - inception
    volumes:
      - database-data:/var/lib/mysql

# ---------------------------------------------- #

  nginx:

    build: requirements/nginx
    container_name: nginx
    restart: on-failure
    depends_on: 
      - wordpress
    env_file: .env
    networks:
      - inception
    ports: 
      - 443:443
    volumes:
      - wordpress-data:/var/www/wordpress:ro

# ----------------------------------------------- #


  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    restart: on-failure
    depends_on: 
      - mariadb
    env_file: .env
    networks:
      - inception
    ports:
      - 9000:9000
    volumes:
      - wordpress-data:/var/www/wordpress

# ------------------------------------------- #

networks:
  inception:

# ------------------------------------------------ #

volumes:
  database-data:
  wordpress-data:
